// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEtJGlvXGY9Pvl1RZUfuK5ih40aJWdw8I',
    appId: '1:898270839438:web:3a1c37278faae9682bffdf',
    messagingSenderId: '898270839438',
    projectId: 'smdcnewdev',
    authDomain: 'smdcnewdev.firebaseapp.com',
    storageBucket: 'smdcnewdev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAo2Cg1VigiSZ63gIKFVP_sSV0puVPHY',
    appId: '1:898270839438:android:85c26180ab338e072bffdf',
    messagingSenderId: '898270839438',
    projectId: 'smdcnewdev',
    storageBucket: 'smdcnewdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRURELBfS-hOrWkBy1sHZ5otMOG-u1YgA',
    appId: '1:898270839438:ios:beb1fcff30852e422bffdf',
    messagingSenderId: '898270839438',
    projectId: 'smdcnewdev',
    storageBucket: 'smdcnewdev.firebasestorage.app',
    iosBundleId: 'com.example.submittalSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRURELBfS-hOrWkBy1sHZ5otMOG-u1YgA',
    appId: '1:898270839438:ios:beb1fcff30852e422bffdf',
    messagingSenderId: '898270839438',
    projectId: 'smdcnewdev',
    storageBucket: 'smdcnewdev.firebasestorage.app',
    iosBundleId: 'com.example.submittalSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARWHC7sOLUGt6d1qLAHrHjpdJm6uGCzvk',
    appId: '1:898270839438:web:21678473eb0f853c2bffdf',
    messagingSenderId: '898270839438',
    projectId: 'smdcnewdev',
    authDomain: 'smdcnewdev.firebaseapp.com',
    storageBucket: 'smdcnewdev.firebasestorage.app',
  );
}
